// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.quizzo.db;

import com.chariot.quizzo.db.Quiz;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Quiz_Roo_Configurable {
    
    declare @type: Quiz: @Configurable;
    
}
