// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.quizzo.model;

import com.chariot.quizzo.model.QuizRun;
import java.io.Serializable;

privileged aspect QuizRun_Roo_Serializable {
    
    declare parents: QuizRun implements Serializable;
    
    private static final long QuizRun.serialVersionUID = 1L;
    
}
