// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariot.quizzo.model;

import com.chariot.quizzo.model.Team;
import java.io.Serializable;

privileged aspect Team_Roo_Serializable {
    
    declare parents: Team implements Serializable;
    
    private static final long Team.serialVersionUID = 1L;
    
}
